### ISSUE TITLE
For stories, text content needs to be extracted from html page content

### ISSUE THREAD

**Issue by arnabbiswas1** [DataKind-BLR/PrathamBooks-Sprint-2018#1]
For stories_pages.csv, "page_content" column consists of the html content of each page. The actual content of the story is needs to be extracted from the html content.

For example for the following html content, the actual story/text content which will be our interest will be "A fawn was racing in the forest." :

> "<p class=""wysiwyg-text-align-left""><span class=""text-font-largest"">A fawn was racing in the forest.</span></p><p class=""wysiwyg-text-align-left""></p><p class=""wysiwyg-text-align-left""></p>"

End result should be: 
1. Modified stories_pages.csv (**Do NOT commit data in github. You may mention data file name in .gitignore so that it does not get committed to github**

2. Script which is used to generate the data (MUST be committed to github)

**Comment by siddjain24** [comment]
Hello @arnabbiswas1 , I can take this up

**Comment by arnabbiswas1** [comment]
@siddjain24 Here you go!
