### ISSUE TITLE
Story Content Data Correction

### ISSUE THREAD

**Issue by githubssn** [DataKind-BLR/PrathamBooks-Sprint-2018#10]
1. The csv file has couple of new lines where the page content is getting split and needs to be corrected. 
2. There are only 2 records of stories created by kids while there are more stories created by kids on the storyweaver portal. 
3. Get data on image text <text below image for story>
4. The story category information should ideally be included in the merged file <story_content.csv> as it will useful for tagging. Also, in the raw data file <stories_categories>, the same story id has multiple categories. Could you please check this?

**Comment by rshenoy21** [comment]
@arnabbiswas1 , On the storyweaver portal, when you select specific stories, you can see the tags they are associated with displayed in the bottom. I guess not all stories have tags as Purvi had mentioned earlier. But wherever they are mentioned, it would be good to include them in the story_content.csv file so we can analyze them as well. I did not see this as a column in the notebook from Sneha.

Also, if you are looking for more hands on this issue, I can help.  This file will be a input for the visualization task I have taken up. Thanks.

**Comment by arnabbiswas1** [comment]
Hi Rajesh...Could you please review the following PR which addresses this issue as well:
https://github.com/DataKind-BLR/PrathamBooks-Sprint-2018/pull/13

For tags, please feel free to explore. Would be happy to chat further on slack.

**Comment by arnabbiswas1** [comment]
Change has been merged using PR https://github.com/DataKind-BLR/PrathamBooks-Sprint-2018/pull/13. Hence closing.
