### ISSUE TITLE
Basic Exploratory Analysis of Stories Data

### ISSUE THREAD

**Issue by arnabbiswas1** [DataKind-BLR/PrathamBooks-Sprint-2018#3]
stories_pages.csv consists of different attributes associated with each stories such as language, reading levels, number of reads, whether publisher created or community created. Basic EDA may be helpful to better understand the data. Following could be some interesting features to visualize: 

"is_child_created_story","stories_status","ancestry","is_recommended_story","reads","language_name","organization_name""story_derivation_type","story_publishing_type","reading_level_cat"

The end result should be a notebook. 

Considering the generic nature of the solution, multiple contributors can be involved. Please add a comment if you are working on it.

**Comment by aparnack** [comment]
I want to work on this. 
Thanks
Aparna

**Comment by arnabbiswas1** [comment]
@aparnack Here you go. However, if any one else is interested, please let us know. We can have multiple members owning the same issue.

**Comment by githubssn** [comment]
i would like to contribute to this task as well

**Comment by arnabbiswas1** [comment]
@githubssn Here you go! 👍

**Comment by arnabbiswas1** [comment]
This has been addressed as a part of https://github.com/DataKind-BLR/PrathamBooks-Sprint-2018/pull/11
